namespace WMI2CSharp.Enums
{
    public enum InformationType
    {
        All,
        BaseBoard,
        BIOS,
        ComputerSystem,
        Desktops,
        Disks,
        DiskDrives,
        DiskPartitions,
        Environments,
        LocalTime,
        NetworkAdapters,
        NetworkAdapterConfigurations,
        OperatingSystem,
        PhysicalMemories,
        PNPEntities,
        PNPSignedDrivers,
        Printers,
        PrinterConfigurations,
        Processes,
        Processor,
        Products,
        QuickFixEngineerings,
        SerialPorts,
        SerialPortConfigurations,
        Services,
        SoftwareLicensingService,
        TimeZone,
        VideoControllers,
        Volumes,
        WindowsScore
    }
}
